name: Development CI form branch

on:
  push:
    branches:
      - main
jobs:
  release:

    runs-on: ubuntu-latest
    if: github.repository == 'zhanghengxin/CasaOS-UI'
    strategy:
      matrix:
        node-version: [ 16.x ]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: '使用 Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: '缓存 Cache'
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}
          
      - name: isntall git
        run: sudo apt install --yes git

      - name: git global
        run: sudo git config --global --add safe.directory '*'
        
      - name: Fetch all tags
        run: sudo git fetch --force --tags
        
      - name: Get version
        id: get_version
        # run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        run: echo "VERSION=$(git describe --abbrev=0 --tags | awk -F- '{print $1}')" >> $GITHUB_ENV

      - name: show version
        id: show_version
        # run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        run: echo ${{env.VERSION}}
   
          
      - run: yarn install
      - run: yarn build
      - run: |
          cp ./build/sysroot/var/lib/casaos/www/img/wallpaper0*.jpg ./build/sysroot/var/lib/casaos/www/ui/img/
          tar -zcvf linux-all-casaos-${{ env.VERSION }}.tar.gz build
      - name: install sshpass
        run: apt install sshpass --yes

      - name: copy tar to target host
        shell: bash
        run: |
          sshpass -p "${{ secrets.ssh_password }}" scp -r -o StrictHostKeyChecking=no -P ${{ secrets.ssh_port }} ./*.gz root@${{ secrets.ssh_ip }}:/var/www/download
          echo "ping success"
